/*
 * generated by Xtext
 */
package qa.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import qa.xtext.ui.internal.QaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return QaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return QaActivator.getInstance().getInjector(QaActivator.QA_XTEXT_QA);
	}
	
}
